import type { Metadata } from "next";
import "./globals.css";
// import DevBanner from "@/components/ambiente-dev";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 10;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="">
        {/* <DevBanner /> */}
        {children}
      </body>
    </html>
  );
}
